# Week 2

1. Q&A
2. Data frames
    - Creating them
    - Indexes and column names
    - Retrieving and setting
    - Methods and attributes we'll want to use
    - `.loc` and mask indexes
3. Creating data frames from files
    - CSV (comma-separated values / character-separated values)
    - Excel
    - JSON
    - Retrieving data from the Internet

In [3]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [4]:
type(pd)

module

# Data frames

If a series is a 1D data structure, with values (that have a dtype) and an index, then a data frame is a 2D data structure. It has rows (the equivalent to a series index) and columns (which also a type of index, but along the tops of the columns).

Each column in a data frame is actually a series.

In [5]:
# create a data frame, using a list of lists

df = DataFrame([[10, 20, 30],
                [40, 50, 60], 
                [70, 80, 90],
                [100, 110, 120]])

df

     0    1    2
0   10   20   30
1   40   50   60
2   70   80   90
3  100  110  120

In [6]:
df.index #  give me the index

RangeIndex(start=0, stop=4, step=1)

In [7]:
df.columns  # give me the columns

RangeIndex(start=0, stop=3, step=1)

In [9]:
# what if I want to set the index or the column names?
# we saw last week that I can pass a list of values for the index
# that continues to be true! And I can do that for the columns, also


df = DataFrame([[10, 20, 30],
                [40, 50, 60], 
                [70, 80, 90],
                [100, 110, 120]],
              index=list('abcd'),
               columns=list('xyz'))

df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [10]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [11]:
df.columns

Index(['x', 'y', 'z'], dtype='str')

In [12]:
# how can I retrieve a row?
# the answer is -- just as we did values in a series
# why? Because the index is per row, just as it was with a series!
# the best way to retrieve? We can use .loc and .iloc

df.loc['b']  # get row with the index b

x    40
y    50
z    60
Name: b, dtype: int64