# Agenda, week 3

1. Q&A
2. Sorting
3. Grouping (basic, advanced)
4. Pivot tables
5. Joining
6. Cleaning our data
7. Plotting
8. AMA (ask me anything)
9. What's next?

# Sorting

What does it mean to *sort* our data?

- We want to order it, typically from smallest to largest *or* from largest to smallest
- When it comes to data in Pandas, we have many more options than just those

In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [3]:
df = pd.read_csv('taxi.csv',                          # load the 10k taxi records
                 index_col=['tpep_pickup_datetime'])  # when creating the data frame, make the pickup datetime the index

df

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-02 11:19:29,2,2015-06-02 11:47:52,1,1.63,-73.954430,40.764141,1,N,-73.974754,40.754093,2,17.0,0.0,0.5,0.00,0.0,0.3,17.80
2015-06-02 11:19:30,2,2015-06-02 11:27:56,1,0.46,-73.971443,40.758942,1,N,-73.978539,40.761909,1,6.5,0.0,0.5,1.00,0.0,0.3,8.30
2015-06-02 11:19:31,2,2015-06-02 11:30:30,1,0.87,-73.978111,40.738434,1,N,-73.990273,40.745438,1,8.0,0.0,0.5,2.20,0.0,0.3,11.00
2015-06-02 11:19:31,2,2015-06-02 11:39:02,1,2.13,-73.945892,40.773529,1,N,-73.971527,40.760330,1,13.5,0.0,0.5,2.86,0.0,0.3,17.16
2015-06-02 11:19:32,1,2015-06-02 11:32:49,1,1.40,-73.979088,40.776772,1,N,-73.982162,40.758999,2,9.5,0.0,0.5,0.00,0.0,0.3,10.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-01 00:12:59,1,2015-06-01 00:24:18,1,2.70,-73.947792,40.814972,1,N,-73.973358,40.783638,2,11.0,0.5,0.5,0.00,0.0,0.3,12.30
2015-06-01 00:12:59,1,2015-06-01 00:28:16,1,4.50,-74.004066,40.747818,1,N,-73.953758,40.779285,1,16.0,0.5,0.5,3.00,0.0,0.3,20.30
2015-06-01 00:13:00,2,2015-06-01 00:37:25,1,5.59,-73.994377,40.766102,1,N,-73.903206,40.750546,2,21.0,0.5,0.5,0.00,0.0,0.3,22.30
2015-06-01 00:13:02,2,2015-06-01 00:19:10,6,1.54,-73.978302,40.748531,1,N,-73.989166,40.762852,2,6.5,0.5,0.5,0.00,0.0,0.3,7.80
2015-06-01 00:13:04,1,2015-06-01 00:36:33,1,5.80,-73.983215,40.726414,1,N,-73.924133,40.701645,1,21.0,0.5,0.5,4.45,0.0,0.3,26.75

In [4]:
# I want to find the shortest trip distances
# I can grab the trip_distance column and run min on it

df['trip_distance'].min()

np.float64(0.0)

In [6]:
# what about the 5 shortest or the 10 shortest?
# to most easily do this, we will invoke the sort_values method on the series

df['trip_distance'].sort_values()  # this returns a new series, based on the original, sorted in ascending order

tpep_pickup_datetime
2015-06-01 00:12:13     0.00
2015-06-04 15:18:09     0.00
2015-06-02 11:23:46     0.00
2015-06-01 00:08:03     0.00
2015-06-01 00:07:43     0.00
                       ...
2015-06-04 15:17:25    34.84
2015-06-02 11:21:03    35.51
2015-06-01 00:02:42    37.20
2015-06-01 00:04:50    60.30
2015-06-01 00:00:58    64.60
Name: trip_distance, Length: 9999, dtype: float64

In [7]:
df['trip_distance'].sort_values().head(5)  # get the 5 smallest values

tpep_pickup_datetime
2015-06-01 00:12:13    0.0
2015-06-04 15:18:09    0.0
2015-06-02 11:23:46    0.0
2015-06-01 00:08:03    0.0
2015-06-01 00:07:43    0.0
Name: trip_distance, dtype: float64

In [10]:
df['trip_distance'].sort_values().head(15)

tpep_pickup_datetime
2015-06-01 00:12:13    0.0
2015-06-04 15:18:09    0.0
2015-06-02 11:23:46    0.0
2015-06-01 00:08:03    0.0
2015-06-01 00:07:43    0.0
2015-06-04 15:23:02    0.0
2015-06-06 16:51:57    0.0
2015-06-04 15:18:40    0.0
2015-06-01 00:03:44    0.0
2015-06-04 15:17:31    0.0
2015-06-02 11:21:38    0.0
2015-06-02 11:32:13    0.0
2015-06-06 16:53:43    0.0
2015-06-01 00:05:05    0.0
2015-06-02 11:31:47    0.0
Name: trip_distance, dtype: float64

In [11]:
# what about the largest values?

df['trip_distance'].sort_values().tail(15)  # keep the sort in ascending order, and get the largest (ending) values

tpep_pickup_datetime
2015-06-04 15:23:01    26.60
2015-06-02 11:29:58    27.35
2015-06-02 11:26:23    27.81
2015-06-02 11:25:26    28.80
2015-06-01 00:09:29    29.30
2015-06-01 00:00:16    29.78
2015-06-01 00:09:14    31.50
2015-06-01 00:00:13    31.90
2015-06-02 11:28:58    32.10
2015-06-01 00:01:19    32.40
2015-06-04 15:17:25    34.84
2015-06-02 11:21:03    35.51
2015-06-01 00:02:42    37.20
2015-06-01 00:04:50    60.30
2015-06-01 00:00:58    64.60
Name: trip_distance, dtype: float64

In [13]:
# another option: sort in *descending* order

df['trip_distance'].sort_values(ascending=False).head(5) # take the first 5 elements/value, after sorting in descending order

tpep_pickup_datetime
2015-06-01 00:00:58    64.60
2015-06-01 00:04:50    60.30
2015-06-01 00:02:42    37.20
2015-06-02 11:21:03    35.51
2015-06-04 15:17:25    34.84
Name: trip_distance, dtype: float64

# Even more sorting!

It's natural to understand what `sort_values` does. But there's another way to sort a data frame (or series) in Pandas, that is to sort the *index*. For that, we have a separate `sort_index` method. The result is a series in which the index is sorted, and the values just come along for the ride.

In [14]:
df['trip_distance'].sort_index()  # we'll get back a new series in which the trips are from earliest to latest.

tpep_pickup_datetime
2015-06-01 00:00:00     1.00
2015-06-01 00:00:00     1.40
2015-06-01 00:00:00     0.90
2015-06-01 00:00:01     8.15
2015-06-01 00:00:01     1.20
                       ...
2015-06-06 16:53:56     1.20
2015-06-06 16:53:56     1.30
2015-06-06 16:53:56    17.36
2015-06-06 16:53:56     0.58
2015-06-06 16:53:57     0.50
Name: trip_distance, Length: 9999, dtype: float64

# When to use each one?

- If you want the largest/smallest values, then `sort_values` is more appropriate and useful.
- If you want to get the values sorted by datetime, or user ID, or address, then you can make that column into the index, and run `sort_index`.

# What about sorting data frames?

Generally speaking, every method that's available on a series is also available on a data frame.

- `sort_index` is easier to understand on a data frame; it works just like on a series, but multiple columns come along for the ride.
- `sort_values` is more complex, because you have many values that you could sort by. You have to specify to Pandas which column you want to sort by.

In [15]:
df.sort_index()

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-01 00:00:00,1,2015-06-01 00:06:12,1,1.00,-73.988739,40.756832,1,N,-73.974701,40.757038,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
2015-06-01 00:00:00,2,2015-06-01 00:00:00,2,1.40,-73.987160,40.738972,1,N,-73.976288,40.755573,2,11.5,0.0,0.5,0.00,0.00,0.3,12.30
2015-06-01 00:00:00,2,2015-06-01 00:00:00,1,0.90,-73.984428,40.737209,1,N,-73.979935,40.749088,1,11.5,1.0,0.5,2.00,0.00,0.3,15.30
2015-06-01 00:00:01,2,2015-06-01 00:24:48,1,8.15,-74.006844,40.730572,1,N,-73.946342,40.811508,1,26.5,0.5,0.5,2.50,0.00,0.3,30.30
2015-06-01 00:00:01,1,2015-06-01 00:08:26,3,1.20,-73.981827,40.770767,1,N,-73.994957,40.764378,2,7.5,0.5,0.5,0.00,0.00,0.3,8.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-06 16:53:56,1,2015-06-06 17:00:40,1,1.20,-73.992592,40.730629,1,N,-73.998161,40.717072,1,6.5,0.0,0.5,2.19,0.00,0.3,9.49
2015-06-06 16:53:56,1,2015-06-06 17:00:10,1,1.30,-73.973396,40.789967,1,N,-73.958511,40.779106,1,6.5,0.0,0.5,1.45,0.00,0.3,8.75
2015-06-06 16:53:56,2,2015-06-06 17:54:22,1,17.36,-73.790520,40.646461,2,N,-73.969048,40.763062,1,52.0,0.0,0.5,10.66,5.54,0.3,69.00
2015-06-06 16:53:56,2,2015-06-06 16:56:18,1,0.58,-73.949013,40.788616,1,N,-73.952942,40.781727,1,4.0,0.0,0.5,0.95,0.00,0.3,5.75
2015-06-06 16:53:57,1,2015-06-06 16:58:39,1,0.50,-73.968719,40.764427,1,N,-73.965042,40.759476,2,5.0,0.0,0.5,0.00,0.00,0.3,5.80

In [17]:
df.sort_values('trip_distance')

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-01 00:12:13,1,2015-06-01 00:13:47,1,0.00,-74.005714,40.740582,1,N,-74.005417,40.740803,3,3.00,0.5,0.5,0.00,0.00,0.3,4.30
2015-06-04 15:18:09,1,2015-06-04 15:18:09,2,0.00,-74.002953,40.749256,1,N,0.000000,0.000000,2,3.00,0.0,0.5,0.00,0.00,0.3,3.80
2015-06-02 11:23:46,2,2015-06-02 11:24:07,4,0.00,-73.956963,40.766392,1,N,-73.956970,40.766418,2,2.50,0.0,0.5,0.00,0.00,0.3,3.30
2015-06-01 00:08:03,2,2015-06-01 00:08:08,1,0.00,-73.962463,40.755138,2,N,-73.962463,40.755138,1,52.00,0.0,0.5,10.56,0.00,0.3,63.36
2015-06-01 00:07:43,1,2015-06-01 00:07:43,1,0.00,-74.007530,40.740753,1,N,0.000000,0.000000,2,5.00,0.5,0.5,0.00,0.00,0.3,6.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-04 15:17:25,2,2015-06-04 17:05:42,1,34.84,-73.787354,40.641670,5,N,-74.177376,40.690781,2,120.00,0.0,0.0,0.00,17.29,0.3,137.59
2015-06-02 11:21:03,2,2015-06-02 12:16:47,1,35.51,-73.789169,40.647758,3,N,-74.176750,40.662647,1,112.00,0.0,0.0,0.00,22.83,0.3,135.13
2015-06-01 00:02:42,1,2015-06-01 00:03:38,1,37.20,-73.550156,41.043472,5,N,-73.550102,41.043495,1,184.00,0.0,0.0,20.00,5.84,0.3,210.14
2015-06-01 00:04:50,1,2015-06-01 01:31:44,1,60.30,-73.994415,40.750603,5,N,-73.420250,41.137344,1,150.00,0.0,0.0,0.00,9.75,0.3,160.05
2015-06-01 00:00:58,1,2015-06-01 01:22:05,1,64.60,0.000000,0.000000,5,N,0.000000,0.000000,2,69.66,0.0,0.0,0.00,10.00,0.3,79.96

In [19]:
# What if I want the dropoff times for the 5 longest trips?

(
    df
    .sort_values('trip_distance')  # sort by the trip distance, in ascending order
    ['tpep_dropoff_datetime']      # grab the one column that's of interest to us
    .tail(5)                       # get the 5 final values, corresponding to the largest trip_distance
)

tpep_pickup_datetime
2015-06-04 15:17:25    2015-06-04 17:05:42
2015-06-02 11:21:03    2015-06-02 12:16:47
2015-06-01 00:02:42    2015-06-01 00:03:38
2015-06-01 00:04:50    2015-06-01 01:31:44
2015-06-01 00:00:58    2015-06-01 01:22:05
Name: tpep_dropoff_datetime, dtype: str

# Can we sort by more than one column?

We saw that when we invoke `sort_values`, we can pass a column name. We've seen, though, that wherever you can pass a single column name (a string) in Pandas, you can also pass a list of column names (a list of strings). We can do that here, too!

In [20]:
(
    df
    .sort_values(['trip_distance', 'total_amount'])  # if two trips have the same trip_distance, then total_amount will break the tie
)

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-02 11:24:35,2,2015-06-02 11:24:40,1,0.00,0.000000,0.000000,1,N,-73.749077,40.707611,3,-2.50,0.0,-0.5,0.0,0.00,-0.3,-3.30
2015-06-02 11:20:23,2,2015-06-02 11:20:23,2,0.00,-73.937851,40.758236,1,N,0.000000,0.000000,2,1.50,0.0,0.5,0.0,0.00,0.3,2.30
2015-06-02 11:19:46,1,2015-06-02 12:26:33,1,0.00,-73.983200,40.766949,1,N,-73.990410,40.766872,2,2.50,0.0,0.5,0.0,0.00,0.3,3.30
2015-06-02 11:24:35,2,2015-06-02 11:24:40,1,0.00,0.000000,0.000000,1,N,-73.749077,40.707611,2,2.50,0.0,0.5,0.0,0.00,0.3,3.30
2015-06-02 11:23:46,2,2015-06-02 11:24:07,4,0.00,-73.956963,40.766392,1,N,-73.956970,40.766418,2,2.50,0.0,0.5,0.0,0.00,0.3,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-04 15:17:25,2,2015-06-04 17:05:42,1,34.84,-73.787354,40.641670,5,N,-74.177376,40.690781,2,120.00,0.0,0.0,0.0,17.29,0.3,137.59
2015-06-02 11:21:03,2,2015-06-02 12:16:47,1,35.51,-73.789169,40.647758,3,N,-74.176750,40.662647,1,112.00,0.0,0.0,0.0,22.83,0.3,135.13
2015-06-01 00:02:42,1,2015-06-01 00:03:38,1,37.20,-73.550156,41.043472,5,N,-73.550102,41.043495,1,184.00,0.0,0.0,20.0,5.84,0.3,210.14
2015-06-01 00:04:50,1,2015-06-01 01:31:44,1,60.30,-73.994415,40.750603,5,N,-73.420250,41.137344,1,150.00,0.0,0.0,0.0,9.75,0.3,160.05
2015-06-01 00:00:58,1,2015-06-01 01:22:05,1,64.60,0.000000,0.000000,5,N,0.000000,0.000000,2,69.66,0.0,0.0,0.0,10.00,0.3,79.96

# Two more sorting methods

These methods are shortcuts for sorting + grabbing the largest and smallest values:

- `nlargest` -- `df.nlargest(columns='trip_distance', n=10)` -- this returns the rows with the 10 largest `trip_distance` values
- `nsmallest`

In [21]:
df.nlargest(columns='trip_distance', n=10)

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-01 00:00:58,1,2015-06-01 01:22:05,1,64.60,0.000000,0.000000,5,N,0.000000,0.000000,2,69.66,0.0,0.0,0.00,10.00,0.3,79.96
2015-06-01 00:04:50,1,2015-06-01 01:31:44,1,60.30,-73.994415,40.750603,5,N,-73.420250,41.137344,1,150.00,0.0,0.0,0.00,9.75,0.3,160.05
2015-06-01 00:02:42,1,2015-06-01 00:03:38,1,37.20,-73.550156,41.043472,5,N,-73.550102,41.043495,1,184.00,0.0,0.0,20.00,5.84,0.3,210.14
2015-06-02 11:21:03,2,2015-06-02 12:16:47,1,35.51,-73.789169,40.647758,3,N,-74.176750,40.662647,1,112.00,0.0,0.0,0.00,22.83,0.3,135.13
2015-06-04 15:17:25,2,2015-06-04 17:05:42,1,34.84,-73.787354,40.641670,5,N,-74.177376,40.690781,2,120.00,0.0,0.0,0.00,17.29,0.3,137.59
2015-06-01 00:01:19,2,2015-06-01 00:40:12,1,32.40,-73.781425,40.644905,2,N,-73.974174,40.731441,1,52.00,0.0,0.5,10.56,0.00,0.3,63.36
2015-06-02 11:28:58,1,2015-06-02 12:13:29,1,32.10,-73.873085,40.774124,4,N,-73.957283,41.098221,1,129.00,0.0,0.5,27.05,5.54,0.3,162.39
2015-06-01 00:00:13,1,2015-06-01 00:41:05,1,31.90,-73.875206,40.770382,5,N,-73.549629,41.043552,1,210.00,0.0,0.0,42.05,0.00,0.3,252.35
2015-06-01 00:09:14,1,2015-06-01 01:03:11,1,31.50,-73.802437,40.677372,5,N,-74.255424,40.745316,2,140.00,0.0,0.0,0.00,9.75,0.3,150.05
2015-06-01 00:00:16,2,2015-06-01 00:40:35,2,29.78,-73.781853,40.644711,2,N,-74.006905,40.707958,1,52.00,0.0,0.5,17.50,5.54,0.3,75.84

# Exercise: Olympic records

This exercise uses a CSV file, `https://files.lerner.co.il/olympic_athlete_events.zip`, with all Olympic athletes until 2020. 

1. Load this file into a Pandas data frame.
2. Find the 10 heaviest athletes ever to compete. What were their names? What teams did they play for?
3. Find the 10 shortest athletes. How old were they, on average?

In [39]:
filename = 'olympic_athlete_events.zip'

# read_csv works just fine with zipfiles, if they contain csv!
df = pd.read_csv(filename,
                usecols=['Weight', 'Team', 'Name', 'Height', 'Age'])  # usecols lets us determine what columns are read + put into a data frame
df

                            Name   Age  Height  Weight            Team
0                      A Dijiang  24.0   180.0    80.0           China
1                       A Lamusi  23.0   170.0    60.0           China
2            Gunnar Nielsen Aaby  24.0     NaN     NaN         Denmark
3           Edgar Lindenau Aabye  34.0     NaN     NaN  Denmark/Sweden
4       Christine Jacoba Aaftink  21.0   185.0    82.0     Netherlands
...                          ...   ...     ...     ...             ...
271111                Andrzej ya  29.0   179.0    89.0        Poland-1
271112                  Piotr ya  27.0   176.0    59.0          Poland
271113                  Piotr ya  27.0   176.0    59.0          Poland
271114        Tomasz Ireneusz ya  30.0   185.0    96.0          Poland
271115        Tomasz Ireneusz ya  34.0   185.0    96.0          Poland

[271116 rows x 5 columns]

In [40]:
# Find the 10 heaviest athletes ever to compete. What were their names? What teams did they play for?

(
    df
    .sort_values('Weight', ascending=False)
    .head(10)
)

                                 Name   Age  Height  Weight           Team
23156               Ricardo Blas, Jr.  25.0   183.0   214.0           Guam
23155               Ricardo Blas, Jr.  21.0   183.0   214.0           Guam
205467              Aytami Ruano Vega  27.0   200.0   198.0          Spain
75031                   Marek Galiski  29.0   200.0   190.0         Poland
237040  Christopher J. "Chris" Taylor  22.0   196.0   182.0  United States
237039  Christopher J. "Chris" Taylor  22.0   196.0   182.0  United States
206352             Valentyn Rusliakov  28.0   187.0   180.0        Ukraine
206004    Leonel Wilfredo Ruz Carmona  29.0   187.0   178.0      Venezuela
94363     Marcus Jerrold "Mark" Henry  25.0   190.0   176.5  United States
94362     Marcus Jerrold "Mark" Henry  21.0   190.0   176.5  United States

In [41]:
(
    df
    .nlargest(columns='Weight', n=10)
)

                                 Name   Age  Height  Weight           Team
23155               Ricardo Blas, Jr.  21.0   183.0   214.0           Guam
23156               Ricardo Blas, Jr.  25.0   183.0   214.0           Guam
205467              Aytami Ruano Vega  27.0   200.0   198.0          Spain
75031                   Marek Galiski  29.0   200.0   190.0         Poland
237039  Christopher J. "Chris" Taylor  22.0   196.0   182.0  United States
237040  Christopher J. "Chris" Taylor  22.0   196.0   182.0  United States
206352             Valentyn Rusliakov  28.0   187.0   180.0        Ukraine
206004    Leonel Wilfredo Ruz Carmona  29.0   187.0   178.0      Venezuela
94362     Marcus Jerrold "Mark" Henry  21.0   190.0   176.5  United States
94363     Marcus Jerrold "Mark" Henry  25.0   190.0   176.5  United States

In [47]:
# Find the 10 shortest athletes. How old were they, on average?

(
    df
    .nsmallest(columns='Height', n=10)
    ['Age']
     .mean()
)

np.float64(18.6)

In [53]:
# we can use the drop_duplicates method to ... remove duplicates

(
    df
    .nlargest(columns='Weight', n=10)
    .drop_duplicates(subset=['Name', 'Team'])
)

                                 Name   Age  Height  Weight           Team
23155               Ricardo Blas, Jr.  21.0   183.0   214.0           Guam
205467              Aytami Ruano Vega  27.0   200.0   198.0          Spain
75031                   Marek Galiski  29.0   200.0   190.0         Poland
237039  Christopher J. "Chris" Taylor  22.0   196.0   182.0  United States
206352             Valentyn Rusliakov  28.0   187.0   180.0        Ukraine
206004    Leonel Wilfredo Ruz Carmona  29.0   187.0   178.0      Venezuela
94362     Marcus Jerrold "Mark" Henry  21.0   190.0   176.5  United States

In [50]:
help(df.drop_duplicates)

Help on method drop_duplicates in module pandas.core.frame:

drop_duplicates(
    subset: Hashable | Iterable[Hashable] | None = None,
    *,
    keep: DropKeep = 'first',
    inplace: bool = False,
    ignore_index: bool = False
) -> DataFrame | None method of pandas.DataFrame instance
    Return DataFrame with duplicate rows removed.

    Considering certain columns is optional. Indexes, including time indexes
    are ignored.

    Parameters
    ----------
    subset : column label or iterable of labels, optional
        Only consider certain columns for identifying duplicates, by
        default use all of the columns.
    keep : {'first', 'last', ``False``}, default 'first'
        Determines which duplicates (if any) to keep.

        - 'first' : Drop duplicates except for the first occurrence.
        - 'last' : Drop duplicates except for the last occurrence.
        - ``False`` : Drop all duplicates.

    inplace : bool, default ``False``
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

    Returns
    -------
    DataFrame or None
        DataFrame with duplicates removed or None if ``inplace=True``.

    See Also
    --------
    DataFrame.value_counts: Count unique combinations of columns.

    Notes
    -----
    This method requires columns specified by ``subset`` to be of hashable type.
    Passing unhashable columns will raise a ``TypeError``.

    Examples
    --------
    Consider dataset containing ramen rating.

    >>> df = pd.DataFrame(
    ...     {
    ...         "brand": ["Yum Yum", "Yum Yum", "Indomie", "Indomie", "Indomie"],
    ...         "style": ["cup", "cup", "cup", "pack", "pack"],
    ...         "rating": [4, 4, 3.5, 15, 5],
    ...     }
    ... )
    >>> df
        brand style  rating
    0  Yum Yum   cup     4.0
    1  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    3  Indomie  pack    15.0
    4  Indomie  pack     5.0

    By default, it removes duplicate rows based on all columns.

    >>> df.drop_duplicates()
        brand style  rating
    0  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    3  Indomie  pack    15.0
    4  Indomie  pack     5.0

    To remove duplicates on specific column(s), use ``subset``.

    >>> df.drop_duplicates(subset=["brand"])
        brand style  rating
    0  Yum Yum   cup     4.0
    2  Indomie   cup     3.5

    To remove duplicates and keep last occurrences, use ``keep``.

    >>> df.drop_duplicates(subset=["brand", "style"], keep="last")
        brand style  rating
    1  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    4  Indomie  pack     5.0

# Grouping

Let's say that I have the taxi data loaded up, and I want to know, for rides with 1 passenger, what was the mean `trip_distance`?

In [57]:
df = pd.read_csv('taxi.csv')

(
    df
    .loc[ pd.col('passenger_count') == 1 ]   #  replaces this: .loc[ df['passenger_count'] == 1 ]
    ['trip_distance']
    .mean()
)

np.float64(3.0923380047176354)

In [58]:
# now do it for trips with 2 passengers

(
    df
    .loc[ pd.col('passenger_count') == 2 ] 
    ['trip_distance']
    .mean()
)

np.float64(3.3843869002284848)

In [59]:
# now do it for trips with 3 passengers

(
    df
    .loc[ pd.col('passenger_count') == 3 ] 
    ['trip_distance']
    .mean()
)

np.float64(3.3423891625615765)

# Grouping is precisely for this problem:

- We have a categorical column with a number of distinct values
- We also have a column with numeric values
- We want to perform an aggregation/calculation for each distinct categorical value, running on the numeric values

For example: I want the mean of `trip_distance` for each distinct value of `passenger_count`

In [60]:
#             categorical       numeric         aggregation method
df.groupby('passenger_count')['trip_distance'].mean()

passenger_count
0    4.600000
1    3.092338
2    3.384387
3    3.342389
4    3.628901
5    3.182712
6    3.170976
Name: trip_distance, dtype: float64

# Examples of where/how to use grouping

- For each country, what was the total number of sales?
- For each salesperson, what was the mean number of sales this year?
- For each product, what is the max price?

You'll always need an aggregation method, typically: `mean`, `median`, `max`, `min`, `sum`, `count`

# Exercise: Olympic grouping

1. For each team, what was the mean athlete height? Which 5 teams were tallest, on average?
2. For each team, what was the number of medals they accumulated? Note that the `count` method ignores `NaN`.

In [61]:
olympics_df = pd.read_csv('olympic_athlete_events.zip')

In [63]:
# For each team, what was the mean athlete height? Which 5 teams were tallest, on average?

# - categorical - team, I want one result for each unique team name
# - numeric - Height
# - aggregation method will be mean

olympics_df.groupby('Team')['Height'].mean()  # this returns a series -- index is team names, values are mean height for each team

Team
30. Februar              171.500000
A North American Team           NaN
Acipactli                174.666667
Acturus                         NaN
Afghanistan              170.592593
                            ...
Zambia                   172.828125
Zefyros                  180.000000
Zimbabwe                 173.325175
Zut                             NaN
rn-2                     176.000000
Name: Height, Length: 1184, dtype: float64

In [64]:
# on a series, we can invoke nlargest, but there are columns, so we just pass a number

(
    olympics_df
    .groupby('Team')['Height'].mean()
    .nlargest(5)
)

Team
Puerto Rico-1           196.000000
England-1               193.000000
France/Great Britain    191.000000
Nadine                  190.000000
Ireland-1               189.666667
Name: Height, dtype: float64

In [68]:
# For each team, what was the number of medals they accumulated? Note that the count method ignores NaN.

# categorical - Team
# to-be-calculated - Medal
# aggregation method - count

(
    olympics_df
    .groupby('Team')['Medal'].count()
    .nlargest(10)
)

Team
United States    5219
Soviet Union     2451
Germany          1984
Great Britain    1673
France           1550
Italy            1527
Sweden           1434
Australia        1306
Canada           1243
Hungary          1127
Name: Medal, dtype: int64

# Next up

- More grouping
- Pivot tables

If you can say, "for every _____, calculate the ____," then that's a `groupby`.

We can be more sophisticated in our grouping, too.

In [69]:
# we want to get the mean trip_distance for every distinct value of passenger_count

#             categorical       numeric         agg method
df.groupby('passenger_count')['trip_distance'].mean()

passenger_count
0    4.600000
1    3.092338
2    3.384387
3    3.342389
4    3.628901
5    3.182712
6    3.170976
Name: trip_distance, dtype: float64

In [70]:
# what if I want to get the mean trip_distance and *also* the mean total_amount?

df.groupby('passenger_count')['total_amount'].mean()

passenger_count
0    25.570000
1    17.368569
2    18.406306
3    17.994704
4    18.881648
5    17.211269
6    17.401355
Name: total_amount, dtype: float64

In [71]:
# we can provide a list of columns inside of the [] -- so yes, we'll have [[ ]]

#            categorical        list of numeric columns          agg method
df.groupby('passenger_count')[['trip_distance', 'total_amount']].mean()

                 trip_distance  total_amount
passenger_count
0                     4.600000     25.570000
1                     3.092338     17.368569
2                     3.384387     18.406306
3                     3.342389     17.994704
4                     3.628901     18.881648
5                     3.182712     17.211269
6                     3.170976     17.401355

# Examples of how we might use this

- For each country, what were the median population and income?
- For each city, what is are the mean family size and sq meters/feet per home?

In [72]:
# What if we want to calculate more than one aggregation method?
# then ... we just put a list there!

#            categorical       numeric            agg methods -- two of them!
df.groupby('passenger_count')['trip_distance'].agg(['mean', 'std'])

                     mean       std
passenger_count
0                4.600000  4.666905
1                3.092338  4.020187
2                3.384387  4.242826
3                3.342389  3.822041
4                3.628901  4.351369
5                3.182712  3.969468
6                3.170976  3.759807

In [73]:
# we can also provide a list of categorical columns
# in this case, I get back a series *but* the index has two parts!
# this is known as a multi-index

df.groupby(['passenger_count', 'VendorID'])['trip_distance'].mean()

passenger_count  VendorID
0                1           4.600000
1                1           2.956456
                 2           3.262967
2                1           3.452027
                 2           3.328849
3                1           3.588535
                 2           3.187189
4                1           3.952239
                 2           3.440522
5                1           4.933333
                 2           3.172553
6                2           3.170976
Name: trip_distance, dtype: float64

# Bottom line:

- we can have 1 or more categoricals
- we can have 1 or more data/numeric columns
- we can have 1 or more aggregation methods

Can we have multiples of more than one of these? YES, but then it gets very complex.

# Exercise: Olympic grouping

1. Load the Olympic data into a data frame.
2. For each sport, find the mean height and weight.
3. For each combination of year and season, find the mean height
4. For each sport, find the mean + std height.

In [74]:
olympics_df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [75]:
# For each sport, find the mean height and weight.

# categorical - sport
# numeric/data - Height + Weight
# agg function: mean

olympics_df.groupby('Sport')[['Height', 'Weight']].mean()

                      Height     Weight
Sport
Aeronautics              NaN        NaN
Alpine Skiing     173.489052  72.068110
Alpinism                 NaN        NaN
Archery           173.203085  70.011135
Art Competitions  174.644068  75.290909
...                      ...        ...
Tug-Of-War        182.480000  95.615385
Volleyball        186.994822  78.900214
Water Polo        184.834648  84.566446
Weightlifting     167.824801  78.726663
Wrestling         172.358586  75.495570

[66 rows x 2 columns]

In [76]:
# For each combination of year and season, find the mean height

# categorical: Year + Season
# numeric/data: Height
# agg function: mean

olympics_df.groupby(['Year', 'Season'])['Height'].mean()

Year  Season
1896  Summer    172.739130
1900  Summer    176.637931
1904  Summer    175.788732
1906  Summer    178.206226
1908  Summer    177.543158
1912  Summer    177.447989
1920  Summer    175.752282
1924  Summer    175.239548
      Winter    172.213483
1928  Summer    175.331770
      Winter    173.975410
1932  Summer    174.371681
      Winter    173.433673
1936  Summer    176.112689
      Winter    172.705882
1948  Summer    176.600190
      Winter    172.293103
1952  Summer    174.183023
      Winter    173.540000
1956  Summer    174.116567
      Winter    172.433140
1960  Summer    173.310287
      Winter    170.701493
1964  Summer    173.690848
      Winter    172.133674
1968  Summer    174.087484
      Winter    173.289689
1972  Summer    174.745758
      Winter    173.463415
1976  Summer    175.053724
      Winter    174.099032
1980  Summer    175.634392
      Winter    174.991354
1984  Summer    175.573516
      Winter    175.390194
1988  Summer    175.683249
      Winter    176.104249
1992  Summer    176.382283
      Winter    175.395332
1994  Winter    175.169862
1996  Summer    175.895121
1998  Winter    174.581369
2000  Summer    176.089721
2002  Winter    174.702451
2004  Summer    175.972850
2006  Winter    174.623172
2008  Summer    176.211062
2010  Winter    174.918182
2012  Summer    176.262469
2014  Winter    174.816670
2016  Summer    176.034266
Name: Height, dtype: float64

In [77]:
# For each sport, find the mean + std height.

# categorical: Sport
# numeric/data: Height
# aggregation function: mean + std

olympics_df.groupby('Sport')['Height'].agg(['mean', 'std'])

                        mean        std
Sport
Aeronautics              NaN        NaN
Alpine Skiing     173.489052   7.848716
Alpinism                 NaN        NaN
Archery           173.203085   8.442945
Art Competitions  174.644068   9.286183
...                      ...        ...
Tug-Of-War        182.480000   6.232442
Volleyball        186.994822  10.456854
Water Polo        184.834648   8.560613
Weightlifting     167.824801   9.949635
Wrestling         172.358586  10.074425

[66 rows x 2 columns]

In [78]:
# what if we go completely bananas, and use multiple items in each portion of the groupby?

# categorical: Year + Season
# numeric/data: Height + Weight
# aggregation methods: mean + std

olympics_df.groupby(['Year', 'Season'])[['Height', 'Weight']].agg(['mean', 'std'])

                 Height                Weight
                   mean        std       mean        std
Year Season
1896 Summer  172.739130  11.152349  71.387755  13.819998
1900 Summer  176.637931   8.386735  74.556962  12.232520
1904 Summer  175.788732   7.875653  72.197279  14.017914
1906 Summer  178.206226   7.284956  75.917073  11.954384
1908 Summer  177.543158   7.479630  75.386128  12.757573
1912 Summer  177.447989   7.228445  73.117450  12.467455
1920 Summer  175.752282   7.786053  73.106157  13.585755
1924 Summer  175.239548   8.004610  71.812018  12.381760
     Winter  172.213483   6.256763  69.560976  10.700581
1928 Summer  175.331770   8.194031  70.941791  12.128684
     Winter  173.975410   8.163073  71.625000   8.514381
1932 Summer  174.371681   8.636896  70.897980  12.006501
     Winter  173.433673   7.478563  67.363636   8.496434
1936 Summer  176.112689   8.703956  71.630363  12.442215
     Winter  172.705882   7.178278  70.051282   9.409718
1948 Summer  176.600190   8.241523  71.942308  11.613152
     Winter  172.293103   6.658133  68.540541   8.487192
1952 Summer  174.183023   9.729799  70.096173  12.458545
     Winter  173.540000   7.539275  69.191275  12.760343
1956 Summer  174.116567   9.704546  70.364200  12.669681
     Winter  172.433140   7.714373  70.554094  11.477027
1960 Summer  173.310287   9.300729  69.393811  11.728450
     Winter  170.701493   8.212623  68.136719   9.774255
1964 Summer  173.690848   9.645464  69.686692  12.312376
     Winter  172.133674   7.827944  69.840134   9.630007
1968 Summer  174.087484   9.870786  69.454786  12.602066
     Winter  173.289689   7.690349  70.261145   9.781389
1972 Summer  174.745758  10.138511  70.086422  13.735635
     Winter  173.463415   8.266821  69.495128  10.189220
1976 Summer  175.053724  10.538078  70.066143  14.603968
     Winter  174.099032   7.919106  70.531490  10.268202
1980 Summer  175.634392  11.429158  70.668078  15.217873
     Winter  174.991354   8.293025  70.968705  10.907749
1984 Summer  175.573516  10.935073  70.058133  14.212113
     Winter  175.390194   8.328522  71.099028  11.216806
1988 Summer  175.683249  11.238938  70.224268  14.836667
     Winter  176.104249   8.105490  72.002725  11.412375
1992 Summer  176.382283  11.178681  71.143607  15.116596
     Winter  175.395332   8.423373  71.116780  12.178114
1994 Winter  175.169862   8.434396  71.062100  12.390243
1996 Summer  175.895121  11.621747  70.903281  15.914547
1998 Winter  174.581369   8.819673  70.943734  13.194045
2000 Summer  176.089721  11.372886  71.119046  15.699955
2002 Winter  174.702451   8.823774  71.197070  13.257178
2004 Summer  175.972850  11.547017  71.280695  15.981144
2006 Winter  174.623172   8.826630  70.519354  12.861560
2008 Summer  176.211062  11.469046  71.397679  15.915855
2010 Winter  174.918182   8.942652  70.740863  13.115907
2012 Summer  176.262469  11.450776  71.319586  15.858117
2014 Winter  174.816670   9.011575  70.760111  13.015123
2016 Summer  176.034266  11.440259  70.988637  15.715083

# Pivot tables

Pivot tables are a famous way to summarize data. They basically let us say, given a data frame:

- select one categorical column
- select a second categorical column
- select a numeric column
- select an aggregation method

The result is a data frame with *two* categorical axes, one in the rows and one in the coi