# Week 2

1. Q&A
2. Data frames
    - Creating them
    - Indexes and column names
    - Retrieving and setting
    - Methods and attributes we'll want to use
    - `.loc` and mask indexes
3. Creating data frames from files
    - CSV (comma-separated values / character-separated values)
    - Excel
    - JSON
    - Retrieving data from the Internet

In [3]:
import pandas as pd   # this means: find pandas.py, load it into memory, but refer to it with the "pd" variable
import numpy as np    
from pandas import Series, DataFrame  # this means: find pandas.py, load it into memory, and assign Series and DataFrame

In [4]:
type(pd)

module

# Data frames

If a series is a 1D data structure, with values (that have a dtype) and an index, then a data frame is a 2D data structure. It has rows (the equivalent to a series index) and columns (which also a type of index, but along the tops of the columns).

Each column in a data frame is actually a series.

In [5]:
# create a data frame, using a list of lists

df = DataFrame([[10, 20, 30],
                [40, 50, 60], 
                [70, 80, 90],
                [100, 110, 120]])

df

     0    1    2
0   10   20   30
1   40   50   60
2   70   80   90
3  100  110  120

In [6]:
df.index #  give me the index

RangeIndex(start=0, stop=4, step=1)

In [7]:
df.columns  # give me the columns

RangeIndex(start=0, stop=3, step=1)

In [9]:
# what if I want to set the index or the column names?
# we saw last week that I can pass a list of values for the index
# that continues to be true! And I can do that for the columns, also


df = DataFrame([[10, 20, 30],
                [40, 50, 60], 
                [70, 80, 90],
                [100, 110, 120]],
              index=list('abcd'),
               columns=list('xyz'))

df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [10]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [11]:
df.columns

Index(['x', 'y', 'z'], dtype='str')

In [12]:
# how can I retrieve a row?
# the answer is -- just as we did values in a series
# why? Because the index is per row, just as it was with a series!
# the best way to retrieve? We can use .loc and .iloc

df.loc['b']  # get row with the index b

x    40
y    50
z    60
Name: b, dtype: int64

In [13]:
df.loc[['b', 'd']]  # fancy indexing, asking for more than one row

     x    y    z
b   40   50   60
d  100  110  120

In [14]:
df.iloc[2]  # get the row at position 2

x    70
y    80
z    90
Name: c, dtype: int64

In [15]:
df.iloc[[1, 3]]

     x    y    z
b   40   50   60
d  100  110  120

In [17]:
# remember slices?

df.loc['b':'d']  # slices with .loc are up to and INCLUDING

     x    y    z
b   40   50   60
c   70   80   90
d  100  110  120

In [18]:
df.iloc[1:3]  # slices with .iloc are the traditional up to and NOT INCLUDING

    x   y   z
b  40  50  60
c  70  80  90

In [19]:
s = Series([10, 20, 30], index=list('abc'))
s

a    10
b    20
c    30
dtype: int64

In [21]:
# how can we retrieve one or more columns?
# answer: with [] 
# that's why I told you last week to use .loc to retrieve from a series index, so you won't get confused here!

df['x']  # get one column

a     10
b     40
c     70
d    100
Name: x, dtype: int64

In [23]:
df[['x', 'z']]   # two columns, aka a data frame

     x    z
a   10   30
b   40   60
c   70   90
d  100  120

In [ ]:
# is there a way to retrieve positionally from the columns, similar to .iloc?
# nope, there isn't.

# remember that the index (rows) can be repeated. Column names can be repeated, but Pandas *really* discourages
# you from doing it, and tries to stop you.

# Exercise: Grocery store

1. Create a data frame describing products in a grocery store. The columns will be `product`, `price`, and `department`. You should have 5 total products. Each will be a new row in the data frame. The index should be the numeric ID for that product. Each product's ID is a 3-digit number.
2. Retrieve the products at positions 0 and 3.
3. Retrieve those same products via their indexes.
4. Retrieve just the `price` column. What is the mean price of items in your store?

In [27]:
df = DataFrame([['apple', 5, 'produce'],
                ['bananas', 3, 'produce' ],
                ['computer', 500, 'electronics' ],
                ['diary', 20, 'books'  ],
                ['elephant', 100, 'pets']],
              index=[123, 124, 345, 456, 789],
              columns='product price department'.split())
df

      product  price   department
123     apple      5      produce
124   bananas      3      produce
345  computer    500  electronics
456     diary     20        books
789  elephant    100         pets

In [28]:
df.iloc[[0, 3]]  # fancy indexing with iloc

    product  price department
123   apple      5    produce
456   diary     20      books

In [29]:
df.loc[[123, 456]]  # fancy indexing with .loc

    product  price department
123   apple      5    produce
456   diary     20      books

In [30]:
# what if I use strings rather than numbers?

df.loc[['123', '456']]

KeyError: "None of [Index(['123', '456'], dtype='str')] are in the [index]"

In [33]:
# Retrieve just the price column. What is the mean price of items in your store?

df['price'].mean()

np.float64(125.6)

In [34]:
df['price'].median()

np.float64(20.0)

In [35]:
# can I assign a new column to our data frame?
# yes! All I have to do is assign, and give the value as a list (or series) of the right length

#              broadcasting to get a new series back
# assignment
df['tax'] = df['price'] * 0.1
df

      product  price   department   tax
123     apple      5      produce   0.5
124   bananas      3      produce   0.3
345  computer    500  electronics  50.0
456     diary     20        books   2.0
789  elephant    100         pets  10.0

In [36]:
# what if I assign to a column that already exists?
# I overwrite the existing column, and replace it

df['tax'] = df['price'] * 0.2

In [37]:
df

      product  price   department    tax
123     apple      5      produce    1.0
124   bananas      3      produce    0.6
345  computer    500  electronics  100.0
456     diary     20        books    4.0
789  elephant    100         pets   20.0

In [38]:
# what if I want to rename a column?
# data frames have *TONS* of methods, and the odds are that you can do what you want
# in this case, df.rename, and pass columns= with a dict argument, {from:to}

df.rename(columns={'tax':'sales_tax'})

      product  price   department  sales_tax
123     apple      5      produce        1.0
124   bananas      3      produce        0.6
345  computer    500  electronics      100.0
456     diary     20        books        4.0
789  elephant    100         pets       20.0

In [39]:
df

      product  price   department    tax
123     apple      5      produce    1.0
124   bananas      3      produce    0.6
345  computer    500  electronics  100.0
456     diary     20        books    4.0
789  elephant    100         pets   20.0

# Method chaining

Pandas methods generally assume that you don't want to change the data frame, but that you instead want to get a new data frame back, reflecting the changes you made.

For example, in the case of `rename`, we got back a new data frame that was different from