# Agenda, week 3

1. Q&A
2. Sorting
3. Grouping (basic, advanced)
4. Pivot tables
5. Joining
6. Cleaning our data
7. Plotting
8. AMA (ask me anything)
9. What's next?

# Sorting

What does it mean to *sort* our data?

- We want to order it, typically from smallest to largest *or* from largest to smallest
- When it comes to data in Pandas, we have many more options than just those

In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [3]:
df = pd.read_csv('taxi.csv',                          # load the 10k taxi records
                 index_col=['tpep_pickup_datetime'])  # when creating the data frame, make the pickup datetime the index

df

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-02 11:19:29,2,2015-06-02 11:47:52,1,1.63,-73.954430,40.764141,1,N,-73.974754,40.754093,2,17.0,0.0,0.5,0.00,0.0,0.3,17.80
2015-06-02 11:19:30,2,2015-06-02 11:27:56,1,0.46,-73.971443,40.758942,1,N,-73.978539,40.761909,1,6.5,0.0,0.5,1.00,0.0,0.3,8.30
2015-06-02 11:19:31,2,2015-06-02 11:30:30,1,0.87,-73.978111,40.738434,1,N,-73.990273,40.745438,1,8.0,0.0,0.5,2.20,0.0,0.3,11.00
2015-06-02 11:19:31,2,2015-06-02 11:39:02,1,2.13,-73.945892,40.773529,1,N,-73.971527,40.760330,1,13.5,0.0,0.5,2.86,0.0,0.3,17.16
2015-06-02 11:19:32,1,2015-06-02 11:32:49,1,1.40,-73.979088,40.776772,1,N,-73.982162,40.758999,2,9.5,0.0,0.5,0.00,0.0,0.3,10.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-01 00:12:59,1,2015-06-01 00:24:18,1,2.70,-73.947792,40.814972,1,N,-73.973358,40.783638,2,11.0,0.5,0.5,0.00,0.0,0.3,12.30
2015-06-01 00:12:59,1,2015-06-01 00:28:16,1,4.50,-74.004066,40.747818,1,N,-73.953758,40.779285,1,16.0,0.5,0.5,3.00,0.0,0.3,20.30
2015-06-01 00:13:00,2,2015-06-01 00:37:25,1,5.59,-73.994377,40.766102,1,N,-73.903206,40.750546,2,21.0,0.5,0.5,0.00,0.0,0.3,22.30
2015-06-01 00:13:02,2,2015-06-01 00:19:10,6,1.54,-73.978302,40.748531,1,N,-73.989166,40.762852,2,6.5,0.5,0.5,0.00,0.0,0.3,7.80
2015-06-01 00:13:04,1,2015-06-01 00:36:33,1,5.80,-73.983215,40.726414,1,N,-73.924133,40.701645,1,21.0,0.5,0.5,4.45,0.0,0.3,26.75

In [4]:
# I want to find the shortest trip distances
# I can grab the trip_distance column and run min on it

df['trip_distance'].min()

np.float64(0.0)

In [6]:
# what about the 5 shortest or the 10 shortest?
# to most easily do this, we will invoke the sort_values method on the series

df['trip_distance'].sort_values()  # this returns a new series, based on the original, sorted in ascending order

tpep_pickup_datetime
2015-06-01 00:12:13     0.00
2015-06-04 15:18:09     0.00
2015-06-02 11:23:46     0.00
2015-06-01 00:08:03     0.00
2015-06-01 00:07:43     0.00
                       ...
2015-06-04 15:17:25    34.84
2015-06-02 11:21:03    35.51
2015-06-01 00:02:42    37.20
2015-06-01 00:04:50    60.30
2015-06-01 00:00:58    64.60
Name: trip_distance, Length: 9999, dtype: float64

In [7]:
df['trip_distance'].sort_values().head(5)  # get the 5 smallest values

tpep_pickup_datetime
2015-06-01 00:12:13    0.0
2015-06-04 15:18:09    0.0
2015-06-02 11:23:46    0.0
2015-06-01 00:08:03    0.0
2015-06-01 00:07:43    0.0
Name: trip_distance, dtype: float64

In [10]:
df['trip_distance'].sort_values().head(15)

tpep_pickup_datetime
2015-06-01 00:12:13    0.0
2015-06-04 15:18:09    0.0
2015-06-02 11:23:46    0.0
2015-06-01 00:08:03    0.0
2015-06-01 00:07:43    0.0
2015-06-04 15:23:02    0.0
2015-06-06 16:51:57    0.0
2015-06-04 15:18:40    0.0
2015-06-01 00:03:44    0.0
2015-06-04 15:17:31    0.0
2015-06-02 11:21:38    0.0
2015-06-02 11:32:13    0.0
2015-06-06 16:53:43    0.0
2015-06-01 00:05:05    0.0
2015-06-02 11:31:47    0.0
Name: trip_distance, dtype: float64

In [11]:
# what about the largest values?

df['trip_distance'].sort_values().tail(15)  # keep the sort in ascending order, and get the largest (ending) values

tpep_pickup_datetime
2015-06-04 15:23:01    26.60
2015-06-02 11:29:58    27.35
2015-06-02 11:26:23    27.81
2015-06-02 11:25:26    28.80
2015-06-01 00:09:29    29.30
2015-06-01 00:00:16    29.78
2015-06-01 00:09:14    31.50
2015-06-01 00:00:13    31.90
2015-06-02 11:28:58    32.10
2015-06-01 00:01:19    32.40
2015-06-04 15:17:25    34.84
2015-06-02 11:21:03    35.51
2015-06-01 00:02:42    37.20
2015-06-01 00:04:50    60.30
2015-06-01 00:00:58    64.60
Name: trip_distance, dtype: float64

In [13]:
# another option: sort in *descending* order

df['trip_distance'].sort_values(ascending=False).head(5) # take the first 5 elements/value, after sorting in descending order

tpep_pickup_datetime
2015-06-01 00:00:58    64.60
2015-06-01 00:04:50    60.30
2015-06-01 00:02:42    37.20
2015-06-02 11:21:03    35.51
2015-06-04 15:17:25    34.84
Name: trip_distance, dtype: float64

# Even more sorting!

It's natural to understand what `sort_values` does. But there's another way to sort a data frame (or series) in Pandas, that is to sort the *index*. For that, we have a separate `sort_index` method. The result is a series in which the index is sorted, and the values just come along for the ride.

In [14]:
df['trip_distance'].sort_index()  # we'll get back a new series in which the trips are from earliest to latest.

tpep_pickup_datetime
2015-06-01 00:00:00     1.00
2015-06-01 00:00:00     1.40
2015-06-01 00:00:00     0.90
2015-06-01 00:00:01     8.15
2015-06-01 00:00:01     1.20
                       ...
2015-06-06 16:53:56     1.20
2015-06-06 16:53:56     1.30
2015-06-06 16:53:56    17.36
2015-06-06 16:53:56     0.58
2015-06-06 16:53:57     0.50
Name: trip_distance, Length: 9999, dtype: float64

# When to use each one?

- If you want the largest/smallest values, then `sort_values` is more appropriate and useful.
- If you want to get the values sorted by datetime, or user ID, or address, then you can make that column into the index, and run `sort_index`.

# What about sorting data frames?

Generally speaking, every method that's available on a series is also available on a data frame.

- `sort_index` is easier to understand on a data frame; it works just like on a series, but multiple columns come along for the ride.
- `sort_values` is more complex, because you have many values that you could sort by. You have to specify to Pandas which column you want to sort by.

In [15]:
df.sort_index()

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-01 00:00:00,1,2015-06-01 00:06:12,1,1.00,-73.988739,40.756832,1,N,-73.974701,40.757038,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
2015-06-01 00:00:00,2,2015-06-01 00:00:00,2,1.40,-73.987160,40.738972,1,N,-73.976288,40.755573,2,11.5,0.0,0.5,0.00,0.00,0.3,12.30
2015-06-01 00:00:00,2,2015-06-01 00:00:00,1,0.90,-73.984428,40.737209,1,N,-73.979935,40.749088,1,11.5,1.0,0.5,2.00,0.00,0.3,15.30
2015-06-01 00:00:01,2,2015-06-01 00:24:48,1,8.15,-74.006844,40.730572,1,N,-73.946342,40.811508,1,26.5,0.5,0.5,2.50,0.00,0.3,30.30
2015-06-01 00:00:01,1,2015-06-01 00:08:26,3,1.20,-73.981827,40.770767,1,N,-73.994957,40.764378,2,7.5,0.5,0.5,0.00,0.00,0.3,8.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-06 16:53:56,1,2015-06-06 17:00:40,1,1.20,-73.992592,40.730629,1,N,-73.998161,40.717072,1,6.5,0.0,0.5,2.19,0.00,0.3,9.49
2015-06-06 16:53:56,1,2015-06-06 17:00:10,1,1.30,-73.973396,40.789967,1,N,-73.958511,40.779106,1,6.5,0.0,0.5,1.45,0.00,0.3,8.75
2015-06-06 16:53:56,2,2015-06-06 17:54:22,1,17.36,-73.790520,40.646461,2,N,-73.969048,40.763062,1,52.0,0.0,0.5,10.66,5.54,0.3,69.00
2015-06-06 16:53:56,2,2015-06-06 16:56:18,1,0.58,-73.949013,40.788616,1,N,-73.952942,40.781727,1,4.0,0.0,0.5,0.95,0.00,0.3,5.75
2015-06-06 16:53:57,1,2015-06-06 16:58:39,1,0.50,-73.968719,40.764427,1,N,-73.965042,40.759476,2,5.0,0.0,0.5,0.00,0.00,0.3,5.80

In [17]:
df.sort_values('trip_distance')

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-01 00:12:13,1,2015-06-01 00:13:47,1,0.00,-74.005714,40.740582,1,N,-74.005417,40.740803,3,3.00,0.5,0.5,0.00,0.00,0.3,4.30
2015-06-04 15:18:09,1,2015-06-04 15:18:09,2,0.00,-74.002953,40.749256,1,N,0.000000,0.000000,2,3.00,0.0,0.5,0.00,0.00,0.3,3.80
2015-06-02 11:23:46,2,2015-06-02 11:24:07,4,0.00,-73.956963,40.766392,1,N,-73.956970,40.766418,2,2.50,0.0,0.5,0.00,0.00,0.3,3.30
2015-06-01 00:08:03,2,2015-06-01 00:08:08,1,0.00,-73.962463,40.755138,2,N,-73.962463,40.755138,1,52.00,0.0,0.5,10.56,0.00,0.3,63.36
2015-06-01 00:07:43,1,2015-06-01 00:07:43,1,0.00,-74.007530,40.740753,1,N,0.000000,0.000000,2,5.00,0.5,0.5,0.00,0.00,0.3,6.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-04 15:17:25,2,2015-06-04 17:05:42,1,34.84,-73.787354,40.641670,5,N,-74.177376,40.690781,2,120.00,0.0,0.0,0.00,17.29,0.3,137.59
2015-06-02 11:21:03,2,2015-06-02 12:16:47,1,35.51,-73.789169,40.647758,3,N,-74.176750,40.662647,1,112.00,0.0,0.0,0.00,22.83,0.3,135.13
2015-06-01 00:02:42,1,2015-06-01 00:03:38,1,37.20,-73.550156,41.043472,5,N,-73.550102,41.043495,1,184.00,0.0,0.0,20.00,5.84,0.3,210.14
2015-06-01 00:04:50,1,2015-06-01 01:31:44,1,60.30,-73.994415,40.750603,5,N,-73.420250,41.137344,1,150.00,0.0,0.0,0.00,9.75,0.3,160.05
2015-06-01 00:00:58,1,2015-06-01 01:22:05,1,64.60,0.000000,0.000000,5,N,0.000000,0.000000,2,69.66,0.0,0.0,0.00,10.00,0.3,79.96

In [19]:
# What if I want the dropoff times for the 5 longest trips?

(
    df
    .sort_values('trip_distance')  # sort by the trip distance, in ascending order
    ['tpep_dropoff_datetime']      # grab the one column that's of interest to us
    .tail(5)                       # get the 5 final values, corresponding to the largest trip_distance
)

tpep_pickup_datetime
2015-06-04 15:17:25    2015-06-04 17:05:42
2015-06-02 11:21:03    2015-06-02 12:16:47
2015-06-01 00:02:42    2015-06-01 00:03:38
2015-06-01 00:04:50    2015-06-01 01:31:44
2015-06-01 00:00:58    2015-06-01 01:22:05
Name: tpep_dropoff_datetime, dtype: str

# Can we sort by more than one column?

We saw that when we invoke `sort_values`, we can pass a column name. We've seen, though, that wherever you can pass a single column name (a string) in Pandas, you can also pass a list of column names (a list of strings). We can do that here, too!

In [20]:
(
    df
    .sort_values(['trip_distance', 'total_amount'])  # if two trips have the same trip_distance, then total_amount will break the tie
)

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-02 11:24:35,2,2015-06-02 11:24:40,1,0.00,0.000000,0.000000,1,N,-73.749077,40.707611,3,-2.50,0.0,-0.5,0.0,0.00,-0.3,-3.30
2015-06-02 11:20:23,2,2015-06-02 11:20:23,2,0.00,-73.937851,40.758236,1,N,0.000000,0.000000,2,1.50,0.0,0.5,0.0,0.00,0.3,2.30
2015-06-02 11:19:46,1,2015-06-02 12:26:33,1,0.00,-73.983200,40.766949,1,N,-73.990410,40.766872,2,2.50,0.0,0.5,0.0,0.00,0.3,3.30
2015-06-02 11:24:35,2,2015-06-02 11:24:40,1,0.00,0.000000,0.000000,1,N,-73.749077,40.707611,2,2.50,0.0,0.5,0.0,0.00,0.3,3.30
2015-06-02 11:23:46,2,2015-06-02 11:24:07,4,0.00,-73.956963,40.766392,1,N,-73.956970,40.766418,2,2.50,0.0,0.5,0.0,0.00,0.3,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-04 15:17:25,2,2015-06-04 17:05:42,1,34.84,-73.787354,40.641670,5,N,-74.177376,40.690781,2,120.00,0.0,0.0,0.0,17.29,0.3,137.59
2015-06-02 11:21:03,2,2015-06-02 12:16:47,1,35.51,-73.789169,40.647758,3,N,-74.176750,40.662647,1,112.00,0.0,0.0,0.0,22.83,0.3,135.13
2015-06-01 00:02:42,1,2015-06-01 00:03:38,1,37.20,-73.550156,41.043472,5,N,-73.550102,41.043495,1,184.00,0.0,0.0,20.0,5.84,0.3,210.14
2015-06-01 00:04:50,1,2015-06-01 01:31:44,1,60.30,-73.994415,40.750603,5,N,-73.420250,41.137344,1,150.00,0.0,0.0,0.0,9.75,0.3,160.05
2015-06-01 00:00:58,1,2015-06-01 01:22:05,1,64.60,0.000000,0.000000,5,N,0.000000,0.000000,2,69.66,0.0,0.0,0.0,10.00,0.3,79.96